name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Убедитесь, что все зависимости указаны

    - name: Simulate test step
      run: echo "No tests found, but CI/CD pipeline runs successfully."

    - name: Complete job
      run: echo "Job completed successfully."
